# Generated by Django 4.2.7 on 2024-01-21 01:42

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cargo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idestudiantes", models.CharField(max_length=50)),
                ("idprofesores", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Estudiante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idestudiantes", models.CharField(max_length=50)),
                ("nombre", models.CharField(max_length=100)),
                ("apellido", models.CharField(max_length=100)),
                ("cedula", models.CharField(max_length=15)),
                ("correoelectronico", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Profesor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idprofesores", models.CharField(max_length=50)),
                ("nombre", models.CharField(max_length=100)),
                ("apellido", models.CharField(max_length=100)),
                ("cedula", models.CharField(max_length=15)),
                ("correoelectronico", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="SistemaWeb",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idsistemaweb", models.CharField(max_length=50)),
                ("actividades", models.CharField(max_length=100)),
                ("calificaciones", models.CharField(max_length=100)),
                ("materias", models.CharField(max_length=15)),
            ],
        ),
    ]
