# Generated by Django 4.2.7 on 2024-01-21 02:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="estudiante",
            name="tipo_usuario",
            field=models.CharField(default="estudiante", max_length=20),
        ),
        migrations.AddField(
            model_name="profesor",
            name="tipo_usuario",
            field=models.CharField(default="docente", max_length=20),
        ),
    ]
